### ISSUE TITLE
question about using the library

### ISSUE THREAD

**Issue by AmichayMiara** [wenbinke/paypal-permissions-sdk-node#4]
Hey wenbinke,

when using

let api = new PermissionsApi({
  mode: 'sandbox', // set "live" for production
  userId: 'xxx',
  password: 'xxx',
  signature: 'xxx',
  appId: 'APP-80W284485P519543T' // my app ID
})

I got an error:
 message: 'Authentication failed. API credentials are incorrect.

It means that I need to fill in the userId, password,signature fields?
its not like Oauth2 that the client connect to paypal after redirect?

**Comment by wesley-firewalla** [comment]
Can you find the information from https://developer.paypal.com/developer/accounts?

Check the following link:

https://stackoverflow.com/questions/2682862/x-paypal-security-userid-password-and-signature

**Comment by AmichayMiara** [comment]
So userId, password,signature is must/needed to use this library?

**Comment by wesley-firewalla** [comment]
right.
